# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NxfNpT1sLmg6-L0bAt4lQ1eFgjWt0_6u
"""

# Commented out IPython magic to ensure Python compatibility.
import os
import numpy as np
import pandas as pd

import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt
# %matplotlib inline
import tensorflow as tf

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA
from sklearn.metrics import euclidean_distances
from scipy.spatial.distance import cdist
from matplotlib import pyplot as plt
from matplotlib.pyplot import plot
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings("ignore")

data = pd.read_csv("/content/data.csv")
genre_data = pd.read_csv('/content/data_by_genres.csv')
year_data = pd.read_csv('/content/data_by_year.csv')
artist_data = pd.read_csv('/content/data_by_artist.csv')

"""# New Section"""

print(data.info())
print(genre_data.info())
print(year_data.info())
print(artist_data.info())

year_data.pivot(index='year', columns='duration_ms', values='energy').head() # Use index, columns, and values keyword arguments instead of positional arguments
plt.figure(figsize=(20,100))
pivot_table = year_data.pivot(index='year', columns='duration_ms', values='energy') # Use index, columns, and values keyword arguments instead of positional arguments
plt.xlabel('year', size = 14)
plt.ylabel('duration_ms', size = 14)
plt.title('Energy over time', size = 14)
sns.heatmap(pivot_table, annot=True, linewidths=.4,linecolor='black', square=True, cmap='Greens_r',cbar=True); # Pass pivot_table to the heatmap function

import pandas as pd

df = pd.read_csv('/content/data.csv')

# Select only numeric columns for correlation calculation
numeric_df = df.select_dtypes(include=['number'])

# Calculate the correlation matrix
corr = numeric_df.corr()

# Display the correlation matrix
print(corr)

plot_df = pd.read_csv('/data.csv')
plot_df.head()
plot_df['explicit'].value_counts(dropna = False)
plot_df.boxplot(column='popularity', by ='explicit')
plt.title('Spotify tracks dataset ')
plt.suptitle('')

sns.boxplot(x='explicit', y='popularity', data=plot_df, palette='Blues' )

data = pd.read_csv('/data.csv')
plt.figure(figsize=(10,8))
sns.regplot(x='duration_ms', y='popularity', data=data, color="Skyblue", truncate=True) # Pass x and y as keyword arguments with data

def outliers(df, ft):
    Q1 = df[ft].quantile(0.25)
    Q3 = df[ft].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 = 1.5 * IQR
    ls = df.index[(df[ft] < lower_bound) | (df[ft] > upper_bound)]
    return ls
index_list = []
for feature in ['popularity']:
    index_list.extend(outliers(plot_df, feature))
def remove(df, ls):
    ls = sorted(set(ls))
    df = df.drop(ls)
    return df
cleaned_df = remove(plot_df, index_list)
sns.boxplot(x='explicit', y='popularity', data = cleaned_df, palette='Blues')

data = pd.read_csv('/data.csv')
data.head()
data.columns
# Check if 'time_signature' is in the columns
print(f"'time_signature' in columns: {'time_signature' in data.columns}")
# If not, try a similar column name or correct the CSV file
# For example, if the column name is 'time

data = pd.read_csv('/data.csv')
# Check for the correct column name
print(data.columns)
# Assuming the correct column name is 'time_signature', verify it's in the columns
if 'time_signature' in data.columns:
    data = data[['time_signature', 'duration_ms']]
    data = pd.DataFrame(data)

    # Now use the 'data' DataFrame instead of 'df'
    plt.scatter(data['time_signature'], data['duration_ms'])
    plt.xlabel('Time')
    plt.ylabel('Duration')
    plt.figure(figsize=(10, 10))
    plt.show()
else:
    print(f"Column 'time_signature' not found in the DataFrame. Available columns: {data.columns.tolist()}")

data = pd.read_csv('/data.csv')
data.head()

train_data, val_and_test_data = train_test_split(data, test_size=0.3)
val_data, test_data = train_test_split(val_and_test_data, test_size=0.5)
print(train_data.shape)
print(val_data.shape)
print(test_data.shape)

print(train_data.head())
print(val_data.head())
print(test_data.head())

!pip install spotipy

import pandas as pd
import numpy as np
import spotipy
from spotipy.oauth2 import SpotifyOAuth
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.neighbors import NearestNeighbors

class RecommendationModel:
    def __init__(self, client_id, client_secret, redirect_uri, scope):
        self.scope = scope
        self.sp = spotipy.Spotify(auth_manager=SpotifyOAuth(
            client_id=client_id,
            client_secret=client_secret,
            redirect_uri=redirect_uri,
            scope=scope
        ))

        self.feature_columns = ['danceability', 'acousticness', 'liveness', 'energy', 'valence', 'tempo']
        self.user_feedback = {
            'liked': set(),
            'disliked': set()
        }

        self.user_top_tracks_df = self.get_user_top_tracks()
        self.personal_vector = self.get_personal_vector_from_listening_history()

    def get_user_top_tracks(self, limit=50, time_range='medium_term'):
        top_tracks = self.sp.current_user_top_tracks(limit=limit, time_range=time_range)
        track_data = []
        for track in top_tracks['items']:
            features = self.sp.audio_features(track['id'])[0]
            if features:
                track_data.append({
                    'id': track['id'],
                    'name': track['name'],
                    'artist': track['artists'][0]['name'],
                    'danceability': features['danceability'],
                    'acousticness': features['acousticness'],
                    'liveness': features['liveness'],
                    'energy': features['energy'],
                    'valence': features['valence'],
                    'tempo': features['tempo'],
                    'popularity': track['popularity'],
                    'genre': ' '.join(self.get_artist_genres(track['artists'][0]['id'])),
                })
        return pd.DataFrame(track_data)

    def get_artist_genres(self, artist_id):
        try:
            artist = self.sp.artist(artist_id)
            return artist.get('genres', [])
        except:
            return []

    def get_personal_vector_from_listening_history(self):
        df = self.user_top_tracks_df.copy()
        if df.empty:
            return np.zeros(len(self.feature_columns))
        scaler = MinMaxScaler()
        scaled_features = scaler.fit_transform(df[self.feature_columns])
        return np.mean(scaled_features, axis=0)

    def update_feedback(self, track_id, liked=True):
        if liked:
            self.user_feedback['liked'].add(track_id)
            self.user_feedback['disliked'].discard(track_id)
        else:
            self.user_feedback['disliked'].add(track_id)
            self.user_feedback['liked'].discard(track_id)

    def aggregate_feedback_vector(self, track_ids):
        vectors = []
        for tid in track_ids:
            try:
                features = self.sp.audio_features(tid)[0]
                if features:
                    vectors.append([
                        features['danceability'],
                        features['acousticness'],
                        features['liveness'],
                        features['energy'],
                        features['valence'],
                        features['tempo']
                    ])
            except:
                continue
        if not vectors:
            return np.zeros(len(self.feature_columns))
        return np.mean(vectors, axis=0)



def generate_personalized_recos(self, df, n_neighbors=10):
    liked_vector = self.aggregate_feedback_vector(self.user_feedback['liked'])
    disliked_vector = self.aggregate_feedback_vector(self.user_feedback['disliked'])

    # Combine listening history and feedback
    combined_vector = self.personal_vector + 0.75 * liked_vector - 0.5 * disliked_vector

    # Normalize dataset features
    scaler = MinMaxScaler()
    df_scaled = df.copy()
    df_scaled[self.feature_columns] = scaler.fit_transform(df_scaled[self.feature_columns])

    # Fit NearestNeighbors
    knn = NearestNeighbors(n_neighbors=n_neighbors, metric='euclidean')
    knn.fit(df_scaled[self.feature_columns])

    # Find nearest neighbors to combined vector
    distances, indices = knn.kneighbors([combined_vector])

    # Retrieve recommended tracks
    recommended_df = df_scaled.iloc[indices[0]].copy()
    recommended_df['distance'] = distances[0]
    return recommended_df.sort_values('distance')

!pip install fuzzywuzzy[speedup]

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import NearestNeighbors
from sklearn.impute import SimpleImputer
from fuzzywuzzy import fuzz

class RecommendationModel:
    def __init__(self, user_top_tracks_df):
        self.feature_columns = ['danceability', 'acousticness', 'liveness', 'energy', 'valence', 'tempo']
        self.user_top_tracks_df = user_top_tracks_df
        self.user_feedback = {
            'liked': set(user_top_tracks_df['id'].values),  # Initially all are liked
            'disliked': set()
        }
        self.personal_vector = self.get_personal_vector_from_listening_history()

    def get_personal_vector_from_listening_history(self):
        df = self.user_top_tracks_df.copy()
        if df.empty:
            return np.zeros(len(self.feature_columns))
        scaler = MinMaxScaler()
        scaled_features = scaler.fit_transform(df[self.feature_columns])
        return np.mean(scaled_features, axis=0)

    def aggregate_feedback_vector(self, track_ids, source_df):
        vectors = []
        for tid in track_ids:
            row = source_df[source_df['id'] == tid]
            if not row.empty:
                vectors.append(row[self.feature_columns].values[0])
        if not vectors:
            return np.zeros(len(self.feature_columns))
        return np.mean(vectors, axis=0)

    def is_similar_artist(self, artist_name, user_artists, threshold=70):
        return any(fuzz.token_set_ratio(artist_name.lower(), artist.lower()) >= threshold for artist in user_artists)

    def generate_personalized_recos(self, all_tracks_df, n_neighbors=10, year_tolerance=3, diversify=True):
        # 1. Extract filter info from user top tracks
        user_genres = set(self.user_top_tracks_df['genre'].dropna().unique())
        user_artists = set(self.user_top_tracks_df['artist'].dropna().unique())
        avg_year = self.user_top_tracks_df['year'].dropna().mean()
        min_year = avg_year - year_tolerance
        max_year = avg_year + year_tolerance

        # 2. Filter by genre, year and popularity
        filtered_df = all_tracks_df[
            (all_tracks_df['genre'].isin(user_genres)) &
            (all_tracks_df['year'] >= min_year) &
            (all_tracks_df['year'] <= max_year) &
            (all_tracks_df['popularity'] >= 50)
        ].copy()

        # 3. Optional artist filter
        if not diversify:
            filtered_df = filtered_df[
                filtered_df['artist'].apply(lambda a: self.is_similar_artist(a, user_artists))
            ]

        if filtered_df.empty:
            print("⚠️ No songs found with matching genre, year, artist (if diversify=False), and popularity filters.")
            return pd.DataFrame()

        # 4. Vector construction
        liked_vector = self.aggregate_feedback_vector(self.user_feedback['liked'], all_tracks_df)
        disliked_vector = self.aggregate_feedback_vector(self.user_feedback['disliked'], all_tracks_df)
        combined_vector = self.personal_vector + 0.75 * liked_vector - 0.5 * disliked_vector

        # 5. Normalize and impute
        scaler = MinMaxScaler()
        imputer = SimpleImputer(strategy='mean')
        filtered_df[self.feature_columns] = scaler.fit_transform(filtered_df[self.feature_columns])
        filtered_df[self.feature_columns] = imputer.fit_transform(filtered_df[self.feature_columns])

        # 6. Nearest Neighbors
        knn = NearestNeighbors(n_neighbors=min(n_neighbors, len(filtered_df)), metric='euclidean')
        knn.fit(filtered_df[self.feature_columns])
        distances, indices = knn.kneighbors([combined_vector])

        recommended_df = filtered_df.iloc[indices[0]].copy()
        recommended_df['distance'] = distances[0]
        return recommended_df.sort_values('distance')

# === Main Script ===
if __name__ == '__main__':
    user_top_df = pd.read_csv('/content/user_top5.csv')
    all_songs_df = pd.read_csv('/content/spotify_data.csv')

    # Create recommendation engine
    engine = RecommendationModel(user_top_tracks_df=user_top_df)

    # Run with diversify=True by default
    recommendations = engine.generate_personalized_recos(all_songs_df, n_neighbors=10, diversify=True)

    if not recommendations.empty:
        print("🎵 Top Recommended Songs:")
        print(recommendations[['name', 'artist', 'genre', 'year', 'popularity', 'track_id', 'distance']])
    else:
        print("❌ No recommendations available based on the filters.")